# requirements.yaml - setup 要件定義書
#
# このファイルは以下を定義する:
#   1. ターゲットユーザー（ペルソナ）
#   2. 前提条件
#   3. ゴール
#   4. 質問フロー（MECE）
#   5. カテゴリ別要件
#   6. 成果物
#
# 更新日: 2025-12-01

version: "1.0.0"

# ==============================================================================
# ターゲットユーザー
# ==============================================================================
target_users:
  primary:
    - id: beginner
      name: 完全初心者
      background: プログラミング未経験、Mac も初めて
      goal: 「アプリを作りたい」という漠然とした希望

    - id: other_lang
      name: 他言語経験者
      background: Python/Java 経験あり、Web 未経験
      goal: 本格的な Web サービスを作りたい

    - id: mac_newbie
      name: Mac 初心者（Web 経験者）
      background: Windows/Linux で開発経験、Mac に移行
      goal: すぐに開発を始めたい

  secondary:
    - id: team_lead
      name: チーム導入担当者
      goal: 複数人に同じ環境を展開したい

# ==============================================================================
# 前提条件
# ==============================================================================
prerequisites:
  hardware:
    - Mac（Intel または Apple Silicon）
    - インターネット接続

  software:
    - macOS 13.0 (Ventura) 以上

  accounts:
    tutorial: [Google アカウント]
    production: []  # フロー中で作成

  knowledge:
    required: なし
    helpful: [他言語経験, コマンドライン基礎]

# ==============================================================================
# ゴール
# ==============================================================================
goals:
  tutorial:
    description: 10分で AI チャットが動く成功体験
    outcome: [ブラウザで動く AI チャット, 開発環境の基礎]
    cost: 0

  production:
    description: 公開可能な Web アプリの開発環境
    outcome: [GitHub リポジトリ, Vercel で公開, サービス連携済み]
    cost: カテゴリによる

# ==============================================================================
# 質問フロー（MECE）
# ==============================================================================
question_flow:
  # -------------------------
  # Phase 0: ルート分岐
  # -------------------------
  phase_0:
    question: "今日の目的は？"
    mece:
      exhaustive: true   # A と B で全ケースをカバー
      exclusive: true    # A と B は排他的（どちらか一方）
    options:
      A:
        label: チュートリアル（体験）
        keywords: [チュートリアル, 体験, 試したい, 学習, 勉強, 練習, とりあえず, まず, 初めて]
        next: tutorial_route
      B:
        label: 本番開発（実際に使うもの）
        keywords: [本番, 実際, 作りたい, サービス, アプリ, 公開, デプロイ, ビジネス]
        next: phase_1

  # -------------------------
  # Phase 1: カテゴリ分岐（本番開発のみ）
  # -------------------------
  phase_1:
    question: "何を作りたいですか？"
    mece:
      exhaustive: true   # unknown でその他をカバー
      exclusive: false   # 複数該当の場合は最初にマッチ
    options:
      static_site:
        label: 静的サイト（ポートフォリオ、LP）
        keywords: [ポートフォリオ, LP, ブログ, ホームページ, 紹介サイト]

      web_app:
        label: Web アプリ（データ保存あり）
        keywords: [アプリ, サービス, ツール, 共有, 友達, 管理]

      saas:
        label: SaaS（課金機能）
        keywords: [SaaS, 課金, サブスク, 有料, ビジネス, 副業, 月額]

      ai_chat:
        label: AI チャット（本番品質）
        keywords: [ChatGPT, AI, チャット, 会話, ボット, GPT]
        warning: 複雑なセットアップ、費用発生

      ios_app:
        label: iOS アプリ
        keywords: [iPhone, iOS, スマホアプリ, モバイル, App Store]

      unknown:
        label: その他/不明
        fallback_to: web_app  # 最も汎用的

    fallback_rule: |
      判断に迷ったら web_app として扱う。
      追加質問はしない。

  # -------------------------
  # 質問しないこと（LLM が決定）
  # -------------------------
  no_questions:
    - 言語: TypeScript（固定）
    - フレームワーク: Next.js（固定）
    - パッケージマネージャ: pnpm（固定）
    - デプロイ先: Vercel（固定）
    - 理由: 選択肢が無限にあるものは LLM が決める

# ==============================================================================
# カテゴリ別要件
# ==============================================================================
categories:
  tutorial:
    description: 費用ゼロ、10分で完了
    tools:
      required: [Homebrew, Node.js, pnpm]
      optional: [VS Code]
    accounts:
      required: [Google AI Studio]
      optional: []
    env_vars: [GOOGLE_GENERATIVE_AI_API_KEY]
    estimated_time: 10min
    cost: 0
    template: null

  static_site:
    description: ポートフォリオ、LP など
    tools:
      required: [Homebrew, Git, Node.js, pnpm, GitHub CLI]
      optional: [VS Code]
    accounts:
      required: [GitHub, Vercel]
      optional: []
    env_vars: []
    estimated_time: 30min
    cost: 0
    template: create-next-app (static export)

  web_app:
    description: データベースを使う Web アプリ
    tools:
      required: [Homebrew, Git, Node.js, pnpm, GitHub CLI]
      optional: [VS Code]
    accounts:
      required: [GitHub, Vercel, Neon]
      optional: [Resend]
    env_vars: [DATABASE_URL]
    estimated_time: 45min
    cost: 0
    template: create-next-app + Prisma

  saas:
    description: 課金機能付き SaaS
    tools:
      required: [Homebrew, Git, Node.js, pnpm, GitHub CLI, Stripe CLI]
      optional: [VS Code]
    accounts:
      required: [GitHub, Vercel, Neon, Stripe, Resend]
      optional: [Supabase]
    env_vars:
      - DATABASE_URL
      - NEXTAUTH_SECRET
      - STRIPE_SECRET_KEY
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      - STRIPE_PRICE_ID
      - STRIPE_WEBHOOK_SECRET
      - RESEND_API_KEY
      - CONTACT_EMAIL
    estimated_time: 60min
    cost: 0 (テストモード)
    template: next-saas-stripe-starter
    auth_options:
      - id: neon_auth
        name: Neon Auth (Stack Auth)
        env_vars: [NEXT_PUBLIC_STACK_PROJECT_ID, NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY, STACK_SECRET_SERVER_KEY]
      - id: supabase_auth
        name: Supabase Auth
        env_vars: [NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY]
      - id: authjs
        name: Auth.js (NextAuth)
        env_vars: [AUTH_SECRET, AUTH_GITHUB_ID, AUTH_GITHUB_SECRET]

  ai_chat:
    description: 本番品質の AI チャット
    tools:
      required: [Homebrew, Git, Node.js, pnpm, GitHub CLI]
      optional: [VS Code]
    accounts:
      required: [GitHub, Vercel, Neon, OpenAI]
      optional: [Upstash Redis]
    env_vars: [DATABASE_URL, OPENAI_API_KEY, AUTH_SECRET]
    estimated_time: 60min
    cost: 従量課金
    template: vercel-ai-chatbot
    warning: 複雑

  ios_app:
    description: iPhone アプリ
    tools:
      required: [Homebrew, Git, Node.js, pnpm, Xcode]
      optional: []
    accounts:
      required: [GitHub]
      optional: [Apple Developer]
    env_vars: []
    estimated_time: 90min
    cost: 0 / $99年（App Store）
    template: create-expo-app

# ==============================================================================
# ツール依存関係
# ==============================================================================
tool_dependencies:
  Homebrew:
    depends_on: []
    install: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    post_install:
      apple_silicon: eval "$(/opt/homebrew/bin/brew shellenv)"
      intel: eval "$(/usr/local/bin/brew shellenv)"

  Git:
    depends_on: [Homebrew]
    install: brew install git

  Node.js:
    depends_on: [Homebrew]
    install: brew install node

  GitHub CLI:
    depends_on: [Homebrew, Git]
    install: brew install gh

  pnpm:
    depends_on: [Node.js]
    install: npm install -g pnpm

  VS Code:
    depends_on: [Homebrew]
    install: brew install --cask visual-studio-code

  Stripe CLI:
    depends_on: [Homebrew]
    install: brew install stripe/stripe-cli/stripe
    post_install: stripe login
    usage: |
      ローカルで Stripe Webhook をテストするために必要:
      stripe listen --forward-to localhost:3000/api/stripe/webhook
      上記コマンドで得られる webhook secret を STRIPE_WEBHOOK_SECRET に設定

  Xcode:
    depends_on: []
    install: Mac App Store（手動）

# ==============================================================================
# アカウント依存関係
# ==============================================================================
account_dependencies:
  GitHub:
    depends_on: []
    url: https://github.com/signup

  Vercel:
    depends_on: [GitHub]
    url: https://vercel.com/signup

  Neon:
    depends_on: [GitHub]
    url: https://console.neon.tech/signup
    provides: DATABASE_URL

  Google AI Studio:
    depends_on: []
    url: https://aistudio.google.com/
    provides: GOOGLE_GENERATIVE_AI_API_KEY

  OpenAI:
    depends_on: []
    url: https://platform.openai.com/
    provides: OPENAI_API_KEY

  Stripe:
    depends_on: []
    url: https://dashboard.stripe.com/register
    provides: [STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET]

  Resend:
    depends_on: [GitHub]
    url: https://resend.com/signup
    provides: RESEND_API_KEY

  Apple Developer:
    depends_on: []
    url: https://developer.apple.com/programs/
    cost: $99/年

# ==============================================================================
# 成果物
# ==============================================================================
deliverables:
  tutorial:
    - AI チャットが動くローカル環境
    - 開発ツール一式

  production:
    - GitHub リポジトリ
    - Vercel で公開されたサイト
    - ローカル開発環境

# ==============================================================================
# ファイル構成
# ==============================================================================
files:
  requirements.yaml:
    purpose: 要件定義書（このファイル）
    type: specification

  GUIDE.md:
    purpose: LLM がユーザーと対話するフロー
    type: procedure

  CATALOG.md:
    purpose: ツール・サービスの知識ベース
    type: knowledge_base

# ==============================================================================
# 検証済みバージョン
# ==============================================================================
verified_versions:
  Node.js: ">=18.0.0"
  pnpm: ">=8.0.0"
  macOS: ">=13.0"
  architecture: [Apple Silicon, Intel]
